# Assignment-2

1. Implement Backpropagation algorithm to train an ANN of configuration __2x2x1__ to achieve __XOR__ function.

__Answer__: Neural network is defined and while training backpropagation algorithm is used for adjusting the weights so that the weights are adjusted making the neural network best fit to data as possible.

The XOR truth table looks like:

| Input      | Output |
| ---------- | ------ |
| 0    ,   0 |   0    |
| 1    ,   0 |   1    |
| 0    ,   1 |   1    |
| 1    ,   1 |   0    |


In [339]:
import numpy as np


def sigmoid( net_output ):
        output = 1 / ( 1 + np.exp(-net_output))
        return output
    
class Layer:
    def __init__(self, neurons, no_of_wghts, layer_no):
        print(f"Layer {layer_no+1} has {neurons} neurons and each neuron has {no_of_wghts} weights connected to it.")
        #create weights array of size (neurons, weights+1)
        self.wght = np.random.normal(size=(neurons, no_of_wghts+1))
        self.layer_no = layer_no+1
        self.grad = np.empty(shape=(neurons, no_of_wghts+1))
        self.delta = np.empty(shape=(1, neurons))
    def activate_h(self, input):
        #adding a single row for bias 
        _, col = input.shape
        # print(input)
        if self.wght.shape[1] == col:
            self.activation = np.dot(input, self.wght.T)
            # print(self.activation)
            self.n_output = sigmoid(self.activation)
            self.n_output = np.c_[self.n_output, np.random.normal(size=(self.n_output.shape[0], 1))]
            return self.n_output
        else:
            raise Exception(f"input {input.shape} and weights {self.wght.shape} shape not valid ")
        
    def activate_o(self, input):
        #adding a single row for bias 
        _, col = input.shape
        # print(input)
        if self.wght.shape[1] == col:
            self.activation = np.dot(input,self.wght.T )
            # print(self.activation)
            self.n_output = sigmoid(self.activation)
            return self.n_output
        else:
            raise Exception(f"input {input.shape} and weights {self.wght.shape} shape not valid ")
        


In [345]:
class Input(Layer):
    def __init__(self, neurons, layer_no):
        self.neurons = neurons
        self.layer_no = layer_no+1
    def activate_h(self, input):
        self.n_output = input

In [350]:

class Network:
    def __init__(self, *args) -> None:
        self.layers = []
        self.total_layers = len(args)
        # print(self.total_layers)
        self.layers.append(Input(args[0],0))
        for l in range(1, self.total_layers):
            self.layers.append(Layer(args[l], args[l-1], l))
        # print(self.layers)
    def forward(self, input):
        input = np.c_[input, np.random.normal(size=(input.shape[0],1))]
        self.input = input
        self.layers[0].activate_h(input)
        for layer_no in range(1, self.total_layers-1):
            input = self.layers[layer_no].activate_h(input)
            # print(input, self.layers[layer_no].layer_no)
        self.output = self.layers[-1].activate_o(input)
        print(self.output, self.layers[-1].layer_no)
    def backward(self, target, learning_rate=1):
        diff = target - self.output
        derivative = self.output * ( 1 - self.output)
        delta = diff * derivative
        # print("output=")
        # print(delta.T  @ self.layers[-2].n_output )
        
        # print("weight=")
        # print(self.layers[-1].wght)
        # print(len(delta[:])) 
        #output layer weight update
        for d in range(len(delta[:])):
            # print("delta=")
            # print(delta[d])
            print("grad_0=")
            grad  = np.dot(delta[d].T[:,np.newaxis], self.layers[-2].n_output[d][np.newaxis,:])
            print(grad)
            self.layers[-1].grad = grad
            self.layers[-1].delta = delta[d]
            # print(self.layers[-2].n_output[d][np.newaxis, :] )
            #finding the gradients for weight update
            for l in range(self.total_layers-1, 1, -1):
                print("weights")
                print(self.layers[l].wght[:, :-1])
                delta_h = np.dot(self.layers[l].delta, self.layers[l].wght[:, :-1]) # don't need the bias for the previous layers' weight update
                deriv_h = (self.layers[l-1].n_output[d] * ( 1- self.layers[l-1].n_output[d]))[np.newaxis, :-1]
                delta_h = delta_h * deriv_h
                # print(delta_h.T, self.layers[l-2].n_output[d][np.newaxis, :]) 
                grad = np.dot(delta_h.T, self.layers[l-2].n_output[d][np.newaxis, :]) 
                self.layers[l-1].grad = grad
                self.layers[l-1].delta = delta_h
                # print(self.layers[l].layer_no)
                # print("delta_h=")
                # print(delta_h)
                # print("grad_h")
                # print(grad)
                # print("hidden=", self.layers[l-1].layer_no)
                # print(self.layers[l-1].n_output[d] * ( 1- self.layers[l-1].n_output[d]))
                # print(self.layers[l].delta.shape,  (self.layers[l-1].n_output[d] * ( 1- self.layers[l-1].n_output[d]))[np.newaxis, :].shape)
                # grad  = np.dot(self.layers[].T[:,np.newaxis], self.layers[self.total_layers-(l+1)].n_output[d][np.newaxis,:])
            
            # print("grad=")
            # print(grad)
        #     update = learning_rate * grad
        #     # print("update=", d)
        #     # print(update)
        #     #iterate through each examples' update array
        #     for u in update:
        #         self.layers[-1].wght[d] += u
        #     print("weightchanged=")
        #     print(self.layers[-1].wght)
                
            #weight update
            for layer in  range(1, self.total_layers):
                pass
                              
       

In [351]:
net = Network(2, 2, 1)
# test = Layer(2, 2, 1)
input = np.array([[1, 0],
                  [0, 1]])
# print(input)
# input = np.array([[1, 0]])
net.forward(input)
net.backward(np.array([[0],
                      [0]]))
# net.backward(np.array([[0, 0, 1, 1]]))
# net.forward(input)
# print(test.layers_wght)
# act = test.wghted_sum(input)
# print(act)
# print(sigmoid(act))

Layer 2 has 2 neurons and each neuron has 2 weights connected to it.
Layer 3 has 1 neurons and each neuron has 2 weights connected to it.
[[0.69861062]
 [0.90203384]] 3
grad_0=
[[-0.04482393 -0.01980102 -0.1394894 ]]
weights
[[0.57638394 1.86301057]]
grad_0=
[[-0.05574229 -0.06806963 -0.04124704]]
weights
[[0.57638394 1.86301057]]


In [205]:
for i in range(5, 1, -1):
    print(i)

5
4
3
2
